begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pgtap;
select plan(19);
insert into profiles(display_name,phone_number,phone_masked,pin_hash,is_admin,is_active) values
 ('043 owner','00000431','00****31',crypt('2468',gen_salt('bf',8)),false,true),('043 member','00000432','00****32',crypt('2468',gen_salt('bf',8)),false,true),('043 other','00000433','00****33',crypt('2468',gen_salt('bf',8)),false,true);
insert into app_sessions(profile_id,token_hash,expires_at) select id,encode(digest('043-'||lower(split_part(display_name,' ',2)),'sha256'),'hex'),now()+interval '1 day' from profiles where display_name like '043 %';
insert into teams(name,team_type,leader_id,is_public,status) select '043 populated','other',id,true,'open' from profiles where display_name='043 owner';
insert into teams(name,team_type,leader_id,is_public,status) select '043 empty','other',id,true,'open' from profiles where display_name='043 owner';
insert into team_members(team_id,profile_id,position,role) select t.id,p.id,1,'leader' from teams t join profiles p on p.display_name='043 owner' where t.name like '043 %';
insert into team_members(team_id,profile_id,position,role) select t.id,p.id,2,'member' from teams t join profiles p on p.display_name='043 member' where t.name='043 populated';
insert into team_shopping_items(team_id,name,position,created_by) select t.id,'043 item',1,p.id from teams t join profiles p on p.display_name='043 owner' where t.name='043 populated';
insert into team_turns(team_id,member_id,position,turn_date,status) select t.id,tm.id,1,current_date,'completed' from teams t join team_members tm on tm.team_id=t.id and tm.role='leader' where t.name='043 populated';
select ok((public.archive_team('043-owner',(select id from teams where name='043 populated'))->'team'->>'is_archived')::boolean,'owner archives active team');
select ok(not (public.get_my_teams('043-owner') @> jsonb_build_array(jsonb_build_object('name','043 populated','is_archived',false))),'archived team is not active');
select ok(public.get_my_teams('043-owner') @> jsonb_build_array(jsonb_build_object('name','043 populated','is_archived',true)),'archived team is listed');
select is((select count(*) from team_turns where team_id=(select id from teams where name='043 populated')),1::bigint,'history remains after archive');
select ok(not (public.remove_team_permanently('043-owner',(select id from teams where name='043 populated'),'reason')->>'removed')::boolean,'populated team deletion is blocked');
select ok((public.restore_team('043-owner',(select id from teams where name='043 populated'))->'team'->>'is_archived')::boolean=false,'owner restores archived team');
select throws_like($$select public.archive_team('043-other',(select id from teams where name='043 populated'))$$,'team not available','non-owner cannot archive');
select throws_like($$select public.restore_team('043-other',(select id from teams where name='043 populated'))$$,'team not available','non-owner cannot restore');
select throws_like($$select public.remove_team_permanently('043-other',(select id from teams where name='043 empty'),'reason')$$,'team not available','non-owner cannot delete');
select throws_like($$select public.remove_team_member('043-owner',(select id from team_members where team_id=(select id from teams where name='043 populated') and role='leader'),'reason')$$,'leader cannot be removed','owner is protected');
select is((public.remove_team_permanently('043-owner',(select id from teams where name='043 empty'),'reason')->>'removed')::boolean,true,'empty team can be deleted');
select is((select count(*) from teams where name='043 empty'),0::bigint,'empty team is gone');
select ok(has_function_privilege('anon','public.archive_team(text,uuid)','EXECUTE'),'anon executes archive RPC');
select ok(not has_function_privilege('authenticated','public.archive_team(text,uuid)','EXECUTE'),'authenticated cannot execute archive RPC');
select ok((select prosecdef from pg_proc where oid='public.remove_team_permanently(text,uuid,text)'::regprocedure),'removal RPC is security definer');
select ok((select 'search_path=public, extensions'=any(proconfig) from pg_proc where oid='public.remove_team_permanently(text,uuid,text)'::regprocedure),'removal RPC has fixed path');
select ok(position('auth.uid' in (select pg_get_functiondef('public.remove_team_permanently(text,uuid,text)'::regprocedure)))=0,'removal RPC has no auth uid');
select ok((select relrowsecurity from pg_class where oid='public.teams'::regclass),'teams RLS remains enabled');
select ok(not has_table_privilege('anon','public.teams','DELETE'),'anon cannot delete teams directly');
select * from finish(); rollback;
